schema_version: "1.0.0"

repository:
  name: test-infra-dryrun
  url: "https://github.com/ashuangiras/test-infra-dryrun"
  type: terraform-root
  has_container_images: false

declared_profiles:
  - PROF-TERRAFORM-ROOT-V1

technology_contexts:
  - github
  - github-actions
  - terraform

waiver_ids: []

compliance_contact: platform-team
last_updated: "2026-07-10"
